name: CI Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check src/
